import React from 'react'
import axios from 'axios'
import Head from 'next/head'

import { BASE_URL } from '../Utilities/Index'
import { NoResults, VideoCard } from '../Components/Index'
import { NextPage } from 'next'
import { Video } from '../../types'

interface IProps {
  videos: Video[]
}

const Home = ({ videos }: IProps) => {
  // console.log(videos)
  return (
    <>
      <Head>
        <title>Soft-Media v2 - Your Social Media</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="shortcut icon" href="/logo.png" />
      </Head>
      <div className="flex flex-col gap-10 videos h-full">
        {videos.length ? (
          videos?.map((video: Video) => (
            <VideoCard
              post={video} isShowingOnHome
              key={video._id}
            />
          ))
        ) : (
          <NoResults
          text={`No Videos`}
          />
        )}
      </div>
    </>
  )
}

// export const getServerSideProps = async ({
//   query: { topic },
// }: {
//   query: { topic: string }
// }) => {
//   let response = await axios.get(`${BASE_URL}/api/Post`)

//   if(topic) {
//     response = await axios.get(`${BASE_URL}/api/Discover/${topic}`);
//   }

//   return {
//     props: { videos: response.data },
//   }
// }

// const Home: NextPage = ({ videos }) => {
//   console.log(videos)
//   return (
//     <>
//       <Head>
//         <title>Soft-Media v2 - Your Social Media</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="favicon" href="/logo.png" />
//       </Head>
//       <h1>Heyy, I am a cat</h1>
//     </>
//   )
// }

export const getServerSideProps = async () => {
  const { data } = await axios.get(`${BASE_URL}/api/Post`)

  return {
    props: { videos: data },
  }
}

export default Home
